Review 1
c3leron366/cpp-peer-review pull request #1
Opened 2023-10-16 13:47 UTC by c3leron366

2023-10-16 17:07 UTC, ademwork requested changes
Не смотря на количество замечаний критичных всего два , но непонятно как с ними программа прошла тесты, их необходимо починить. Код хорошо оформлен и читаем, хотелось бы чуть больше комментариев.

2023-10-16 17:07 UTC, ademwork commented on task1.cpp
> +        pages_to_id.reserve(MAX_USERS);
Здесь  надо делать resize вектора , вместо reserve. Reserve выделяет место в памяти , но не изменяет размер самого  вектора.

2023-10-16 17:07 UTC, ademwork commented on task1.cpp
> +        id_to_pages.reserve(MAX_PAGES);
Здесь так же надо заменить reserve на resize.

2023-10-16 17:07 UTC, ademwork commented on task1.cpp
> +            pages_to_id[id_to_pages[user_id]] -= 1;
Здесь и далее , обращение к элементу вектору через индекс , при том что размер вектора 0, то есть обращение к несуществующему элементу.

2023-10-16 17:07 UTC, ademwork commented on task1.cpp
> +        for(int i = 0; i < pages_to_id.capacity(); i++)
capacity лучше заменить на size(), но после замены reserve() на resize() в конструкторе структуры.

2023-10-16 17:07 UTC, ademwork commented on task1.cpp
> +void parse(std::istream& input, BookStorage& storage)
Название функции лучше сделать с большой буквы. В параметр добавить не только входящий поток , но и поток вывода , чтобы было удобнее протестировать.

2023-10-16 17:07 UTC, ademwork commented on task1.cpp
> +        if(s.find("CHEER") != std::string::npos)
Для улучшения быстродействия лучше использовать else if , после того как в строке нашелся READ CHEER там уже не должно быть, а сейчас выполняется повторный не нужный поиск.

2023-10-16 17:07 UTC, ademwork commented on task1.cpp
> +            std::cout << std::setprecision(6) << storage.GetUserStat(id) << std::endl;
std::setprecision(6) можно задать один раз перед циклом, также для улучшения быстродействия.

2023-10-16 17:07 UTC, ademwork commented on task1.cpp
> +std::string test_input =
Желательно добавить к тестовой входящей строке  и строку которая должна получиться в выходном потоке,  все это оформить как функцию юнит теста, будет очень удобно , и не надо будет раскомментировать в main  разные ветки поведения программы. Либо вообще убрать код для теста.

2023-10-16 17:07 UTC, ademwork commented on task1.cpp
> +        auto [a, is_inserted] = user_ids.insert(user_id);
переменную "а" лучше заменить на "_" , чтобы не пытаться искать её использование в коде.

2023-10-16 17:07 UTC, ademwork commented on task1.cpp
> +struct BookStorage
Лучше оформить структуру как класс  и разделить методы и данные на public:  и private: , сейчас все данные общедоступны для изменения.

2023-10-16 17:07 UTC, ademwork commented on task1.cpp
> +    void AddReadedPages(int user_id, int pages)
отсутствуют проверки на соответствие user_id и pages максимальным константам.

2023-10-16 17:07 UTC, ademwork commented on task1.cpp
> +        pages_to_id[pages] += 1;
pages_to_id размером MAX_USERS , то есть 1001 , а индекс обращения pages , который может быть до 100001, здесь явно возможен выход на границы массива. Скорее всего pages_to_id должен быть размером MAX_PAGES, id_to_pages размером MAX_USERS.

2023-10-16 17:58 UTC, ademwork commented on task1.cpp
> +        pages_to_id[pages] += 1;
Когда исправлял твои замечания понял , что размерности векторов правильные , неправильные названия констант.

2023-10-16 18:03 UTC, ademwork commented on task1.cpp
> +    constexpr static int MAX_PAGES = 100001;
По условию задачи - "номера пользователей не превосходят 10⁵, а номера страниц не превосходят 1000", а здесь наоборот.

2023-10-17 08:01 UTC, c3leron366 commented on task1.cpp
> +    void AddReadedPages(int user_id, int pages)
Добавил

2023-10-17 08:01 UTC, c3leron366 commented on task1.cpp
> +            pages_to_id[id_to_pages[user_id]] -= 1;
Исправил

2023-10-17 08:02 UTC, c3leron366 commented on task1.cpp
> +        pages_to_id[pages] += 1;
Здесь было перепутано, да

2023-10-17 11:22 UTC, ademwork requested changes
top_readed_pages необходимо обнулить в конструкторе , без этого программа не проходит тесты на тренажере, а так все хорошо.

2023-10-17 11:22 UTC, ademwork commented on task1.cpp
> +    int top_readed_pages;
Переменной не задано начальное значение.

2023-10-17 11:22 UTC, ademwork commented on task1.cpp
> +    constexpr static int MAX_PAGES = 1000;
constexpr  это команда компилятору вычислить константу на этапе компиляции, но здесь простые числа , их не надо вычислять , можно обойтись const.

2023-10-17 17:47 UTC, ademwork approved these changes
Всё отлично.

2023-10-22 15:52 UTC, merged