Review 3
c3leron366/cpp-peer-review pull request #2
Opened 2023-10-16 13:52 UTC by c3leron366

2023-10-27 17:10 UTC, ademwork requested changes
В общем хорошо , насколько возможно в условиях проверки без остальной программы , но замечания надо поправить.

2023-10-27 17:10 UTC, ademwork commented on CheckDateTimeValidity.cpp
> +struct Constraints
Здесь напрашивается класс , причем dt_ , max_ и min_  сделать приватными.

2023-10-27 17:10 UTC, ademwork commented on CheckDateTimeValidity.cpp
> +        max_.day = max.month_lengths[dt.month - 1];
что за переменная max  ? Наверное должно быть max_.day = month_lengths[dt.month - 1]; .

2023-10-27 17:10 UTC, ademwork commented on LoadPerson.cpp
> +              << "and Name like '%"s << db.Quote(person_params.name_filter) << "%'"s;
переменная db не определена в данном контексте.

2023-10-27 17:10 UTC, ademwork commented on LoadPerson.cpp
> +    if (!db.IsOK())
Если db_allow_exceptions = true, тогда проверка !db.IsOK() не должна проводиться.

2023-10-27 17:10 UTC, ademwork commented on ParseCitySubjson.cpp
> +                        const CountryParams cp, const vector<Language>& languages) {
cp лучше передавать по ссылке , будет только одно копирование, а можно вообще обойтись без копирований.

2023-10-28 05:30 UTC, c3leron366 commented on LoadPerson.cpp
> +              << "and Name like '%"s << db.Quote(person_params.name_filter) << "%'"s;
добавил передачу аргумента функции

2023-10-28 05:31 UTC, c3leron366 commented on CheckDateTimeValidity.cpp
> +struct Constraints
сделал

2023-10-28 05:31 UTC, c3leron366 commented on LoadPerson.cpp
> +    if (!db.IsOK())
исправил

2023-10-28 05:31 UTC, c3leron366 commented on ParseCitySubjson.cpp
> +                        const CountryParams cp, const vector<Language>& languages) {
исправил

2023-10-28 05:31 UTC, c3leron366 commented on CheckDateTimeValidity.cpp
> +        max_.day = max.month_lengths[dt.month - 1];
исправил

2023-10-28 07:39 UTC, ademwork requested changes
Осталась пара опечаток, но без их устранения программа не собралась бы .

2023-10-28 07:39 UTC, ademwork commented on CheckDateTimeValidity.cpp
> +    Constraints& SetMinTimeConstraint(const DateTime& max)
Должно быть SetMaxTimeConstraint ?

2023-10-28 07:39 UTC, ademwork commented on CheckDateTimeValidity.cpp
> +        max_.day = max_.month_lengths[dt.month - 1];
Должно быть max_.day = month_lengths[dt.month - 1]; ?

2023-10-28 07:40 UTC, c3leron366 commented on CheckDateTimeValidity.cpp
> +    Constraints& SetMinTimeConstraint(const DateTime& max)
да

2023-10-28 07:40 UTC, c3leron366 commented on CheckDateTimeValidity.cpp
> +        max_.day = max_.month_lengths[dt.month - 1];
точно

2023-10-28 07:44 UTC, ademwork approved these changes
Все хорошо.

2023-10-28 09:07 UTC, merged